---
title: "Exam I"
output:
  html_document:
    css: ~/GitHub/IALSA-2015-Portland/libs/css/sidebar.css
    keep_md: yes
    toc: yes
  pdf_document:
    toc: yes
  word_document: default
---

<!-- These two chunks should be added in the beginning of every .Rmd that you want to source an .R script -->
<!--  The 1st mandatory chunck  -->
<!--  Set the working directory to the repository's base directory -->
```{r, echo=F, message=F} 
#Don't combine this call with any other chunk 
# cat("Working directory: ", getwd()) # check where you are
  library(knitr)
# Rmd is in "./reports/reportA/reportA.Rmd", but now the root is "./"
  knitr::opts_knit$set(root.dir='../../../') 
```

<!--  The 2nd mandatory chunck  -->
<!-- Set the report-wide options, and point to the external code file. -->
```{r set_options, echo=F}
# set options shared by all chunks
opts_chunk$set(
  results='show', 
  message = TRUE,
  comment = NA, 
  tidy = FALSE,
  fig.height = 4, 
  fig.width = 5.5, 
  out.width = "550px",
  fig.path = 'exam_i_grades/',     
  dev = "png",
  dpi = 100
  # fig.path = 'figure_pdf/',     
  # dev = "pdf"#,
  # dev.args=list(pdf = list(colormodel = 'cmyk'))
)
echoChunks <- FALSE
echoWarnings <- FALSE
options(width=120) #So the output is 50% wider than the default.
# connect to the file with the underlying R script  
read_chunk("./materials/evaluation/exam_i/exam_i.R") 
```






```{r load_sources, echo=echoChunks, message=FALSE}
```


```{r load_packages, echo=echoChunks, message=FALSE}
```


```{r declare_globals, echo=echoChunks, results='show', message=FALSE}
```


```{r load_custom, echo=echoChunks, message=FALSE}
#Put code in here.  It doesn't call a chunk in the codebehind file.
```

We load the data from a private, secure location and de-identify it
```{r load_data, echo=echoChunks, results='show', message=FALSE}
```

Compute the total score for the exam
```{r tweak_data, echo=TRUE, results='show', message=FALSE}
```

## Basic stats
Get basic statistical summary for each item
```{r summary_stats, echo=echoChunks, results='show', message=FALSE}
```

```{r basic_graph, echo=echoChunks, results='show', message=FALSE, eval=FALSE}
```


# grades 
```{r grade_graphs, echo=echoChunks, results='show', message=FALSE, warning=FALSE}
```

