---
title: "Encyclopedia of Historical Datasets"
output: 
  html_document: 
    highlight: pygments
    keep_md: yes
    number_sections: yes
    theme: readable
    toc: yes
---


<!--  The 1st mandatory chunck  -->
<!--  Set the working directory to the repository's base directory -->
```{r, echo=F, message=F} 
#Don't combine this call with any other chunk 
# cat("Working directory: ", getwd()) # check where you are
  library(knitr)
# Rmd is in "./reports/reportA/reportA.Rmd", but now the root is "./"
  knitr::opts_knit$set(root.dir='../../') 
```

<!--  The 2nd mandatory chunck  -->
<!-- Set the report-wide options, and point to the external code file. -->
```{r set_options, echo=F}
# connect to the file with the underlying R script  
read_chunk("./data/HistData/Encyclopedia_HistData.R") 
# set options shared by all chunks
opts_chunk$set(
  results='show', 
  comment = NA, 
  tidy = FALSE,
#   fig.width = 6.5, 
#   fig.height = 4, 
  fig.path = 'figure_HistData/'
)
# dpi = 400,
# out.width = "650px", #This affects only the markdown, not the underlying png file.  The height will be scaled appropriately.

echoChunks <- FALSE
```




<!-- Load the sources.  Suppress the output when loading sources. --> 
```{r load_sources, echo=echoChunks, message=FALSE}
```

<!-- Load 'sourced' R files.  Suppress the output when loading packages. --> 
```{r load_packages, echo=echoChunks, message=FALSE}
```

<!-- Load any Global functions and variables declared in the R file.  Suppress the output. --> 
```{r declare_globals, echo=echoChunks, results='show', message=FALSE}
```

<!-- Declare any global functions specific to a Rmd output.  Suppress the output. --> 
```{r, echo=echoChunks, message=FALSE}
#Put code in here.  It doesn't call a chunk in the codebehind file.
```

<!-- Load the datasets.   -->
```{r load_data, echo=echoChunks, results='show', message=FALSE}
```

<!-- Tweak the datasets.   -->
```{r tweak_data, echo=echoChunks, results='show', message=FALSE}
```


<!-- Basic table view.   -->
```{r basic_table, echo=TRUE, results='show', message=FALSE}
```

<!-- Basic graph view.   -->
```{r basic_graph, echo=TRUE, results='show', message=FALSE}
```


## Galton
<!-- Basic graph view.   -->
```{r Galton_1, echo=echoChunks, fig.height=3.5, fig.width=2, out.width="200px"}
```

<!-- Basic graph view.   -->
```{r Galton_2, echo=echoChunks, fig.height=3.5, fig.width=2, out.width="200px"}
```

<!-- Basic graph view.   -->
```{r Galton_2, echo=echoChunks, fig.height=3.5, fig.width=2, out.width="600px"}
```





