##Chapter 1: Introduction 
(slides, playlist)

Opening Remarks and Examples (18:18)
Supervised and Unsupervised Learning (12:12)


##Chapter 2: Statistical Learning 
(slides, playlist)

Statistical Learning and Regression (11:41)
Curse of Dimensionality and Parametric Models (11:40)
Assessing Model Accuracy and Bias-Variance Trade-off (10:04)
Classification Problems and K-Nearest Neighbors (15:37)
Lab: Introduction to R (14:12)
Chapter 3: Linear Regression (slides, playlist)

Simple Linear Regression and Confidence Intervals (13:01)
Hypothesis Testing (8:24)
Multiple Linear Regression and Interpreting Regression Coefficients (15:38)
Model Selection and Qualitative Predictors (14:51)
Interactions and Nonlinearity (14:16)
Lab: Linear Regression (22:10)
Chapter 4: Classification (slides, playlist)

Introduction to Classification (10:25)
Logistic Regression and Maximum Likelihood (9:07)
Multivariate Logistic Regression and Confounding (9:53)
Case-Control Sampling and Multiclass Logistic Regression (7:28)
Linear Discriminant Analysis and Bayes Theorem (7:12)
Univariate Linear Discriminant Analysis (7:37)
Multivariate Linear Discriminant Analysis and ROC Curves (17:42)
Quadratic Discriminant Analysis and Naive Bayes (10:07)
Lab: Logistic Regression (10:14)
Lab: Linear Discriminant Analysis (8:22)
Lab: K-Nearest Neighbors (5:01)
Chapter 5: Resampling Methods (slides, playlist)

Estimating Prediction Error and Validation Set Approach (14:01)
K-fold Cross-Validation (13:33)
Cross-Validation: The Right and Wrong Ways (10:07)
The Bootstrap (11:29)
More on the Bootstrap (14:35)
Lab: Cross-Validation (11:21)
Lab: The Bootstrap (7:40)
Chapter 6: Linear Model Selection and Regularization (slides, playlist)

Linear Model Selection and Best Subset Selection (13:44)
Forward Stepwise Selection (12:26)
Backward Stepwise Selection (5:26)
Estimating Test Error Using Mallow's Cp, AIC, BIC, Adjusted R-squared (14:06)
Estimating Test Error Using Cross-Validation (8:43)
Shrinkage Methods and Ridge Regression (12:37)
The Lasso (15:21)
Tuning Parameter Selection for Ridge Regression and Lasso (5:27)
Dimension Reduction (4:45)
Principal Components Regression and Partial Least Squares (15:48)
Lab: Best Subset Selection (10:36)
Lab: Forward Stepwise Selection and Model Selection Using Validation Set (10:32)
Lab: Model Selection Using Cross-Validation (5:32)
Lab: Ridge Regression and Lasso (16:34)
Chapter 7: Moving Beyond Linearity (slides, playlist)

Polynomial Regression and Step Functions (14:59)
Piecewise Polynomials and Splines (13:13)
Smoothing Splines (10:10)
Local Regression and Generalized Additive Models (10:45)
Lab: Polynomials (21:11)
Lab: Splines and Generalized Additive Models (12:15)
